### ISSUE TITLE
Out of memory error 请问如何解决啊 

### ISSUE THREAD

**Issue by Merlin-xy** [JiehangXie/PaddleBoBo#23]
```
Traceback (most recent call last):
  File "E:/Graduate/PaddleBoBo-develop/create_virtual_human.py", line 23, in <module>
    cvh = FOM(GAN_Config['FOM_INPUT_IMAGE'],GAN_Config['FOM_DRIVING_VIDEO'],GAN_Config['FOM_OUTPUT_VIDEO'])
  File "E:\Graduate\PaddleBoBo-develop\PaddleTools\GAN.py", line 24, in FOM
    first_order_predictor.run(source_image, driving_video)
  File "E:\Python\environment\lib\site-packages\ppgan\apps\first_order_predictor.py", line 184, in run
    bboxes = self.extract_bbox(source_image.copy())
  File "E:\Python\environment\lib\site-packages\ppgan\apps\first_order_predictor.py", line 324, in extract_bbox
    predictions = detector.get_detections_for_image(np.array(frame))
  File "E:\Python\environment\lib\site-packages\ppgan\faceutils\face_detection\api.py", line 90, in get_detections_for_image
    detected_faces = self.face_detector.detect_from_batch(images.copy())
  File "E:\Python\environment\lib\site-packages\ppgan\faceutils\face_detection\detection\sfd\sfd_detector.py", line 56, in detect_from_batch
    bboxlists = batch_detect(self.face_detector, images)
  File "E:\Python\environment\lib\site-packages\ppgan\faceutils\face_detection\detection\sfd\detect.py", line 76, in batch_detect
    olist = net(imgs)
  File "E:\Python\environment\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "E:\Python\environment\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\Python\environment\lib\site-packages\ppgan\faceutils\face_detection\detection\sfd\net_s3fd.py", line 133, in forward
    h = F.relu(self.conv1_1(x))
  File "E:\Python\environment\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "E:\Python\environment\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\Python\environment\lib\site-packages\paddle\nn\layer\conv.py", line 665, in forward
    out = F.conv._conv_nd(
  File "E:\Python\environment\lib\site-packages\paddle\nn\functional\conv.py", line 123, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
SystemError: (Fatal) Operator conv2d raises an struct paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 297.650635MB memory on GPU 0, 1.821357GB memory has been allocated and available memory is only 182.805861MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:79)
. (at ..\paddle\fluid\imperative\tracer.cc:221)
```
提示GPU内存不够 然后提供了两种解决方案：
- 一是在另外一个GPU运行，我尝试过
`import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'`
但还是相同的报错
- 二是减少batch_size，我尽可能搜索网站信息没有找到如何改变batch_size的帖子，在这个项目里面我没有找到batch_size的关键词，后来我又在项目外（paddle中搜索）结果也不尽人意，尝试过很多比如直接添加batch_size=1，运行无果。甚至`Out of memory error on GPU 0. Cannot allocate 297.650635MB memory on GPU 0, 1.821357GB memory has been allocated and available memory is only 182.805861MB.`这些数值都没有改变。
小白在线求大佬们解惑~！

**Comment by Merlin-xy** [comment]
已经解决了...解决方案就是不在我电脑上跑了....在线云端跑，真香

**Comment by energy888666** [comment]
我的本地gpu 是英伟达2080ti的,GPU 内存 11g  为什么 还是有这个报错呢?

**Comment by JiehangXie** [comment]
显存不足，建议使用aistudio上的teslaV100 32G



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小张学Python ***@***.***&gt;
发送时间: 2022年4月24日 11:23
收件人: JiehangXie/PaddleBoBo ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [JiehangXie/PaddleBoBo] Out of memory error 请问如何解决啊  (Issue #23)






我的本地gpu 是英伟达2080ti的,GPU 内存 11g  为什么 还是有这个报错呢?
